--temp 1.0
--top-p 0.9

[mlx]
--max-tokens 4096

[mlx.serve]
--top-k 64
--min-p 0.05

[llama.cpp]
-ngl all
-c 32768
-np 1
-fa on
-ctk q8_0
-ctv q8_0
-b 2048
-ub 512
--mlock
--reasoning auto
--top-k 64
--min-p 0.05
--repeat-penalty 1.05
--presence-penalty 0.0
--frequency-penalty 0.0

[llama.cpp.serve]
--cache-reuse 256
--cache-prompt
