--temp 0.7
--top-p 0.9

[mlx]
--max-tokens 1024

[mlx.serve]
--top-k 50
--min-p 0.05

[llama.cpp]
-ngl all
-c 8192
-np 1
-fa on
-b 2048
-ub 512
--reasoning auto
--top-k 50
--min-p 0.05
--repeat-penalty 1.05
--presence-penalty 0.0
--frequency-penalty 0.0

[llama.cpp.serve]
--cache-reuse 256
--cache-prompt
