--temp 0.3
--top-p 0.9

[mlx]
--max-tokens 2048

[mlx.serve]
--top-k 40
--min-p 0.0

[llama.cpp]
-ngl all
-c 65536
-np 1
-fa on
-ctk q8_0
-ctv q8_0
-b 2048
--n-predict 2048
-ub 512
--reasoning auto
--top-k 40
--min-p 0.0
--repeat-penalty 1.03
--presence-penalty 0.0
--frequency-penalty 0.0

[llama.cpp.serve]
--cache-reuse 256
--cache-prompt
