#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_PATH="${ROOT_DIR}/src/yallama.sh"
DEFAULT_OUTPUT_PATH="${ROOT_DIR}/yallama"

MODULES=(
  "lib/yallama-cache.sh"
  "lib/yallama-profiles.sh"
  "lib/yallama-runtime.sh"
  "lib/yallama-search.sh"
  "lib/yallama-completions.sh"
)

usage() {
  cat <<EOF
Usage: $(basename "$0") [--output <path> | --stdout | --check]

Options:
  --output <path>  Write the generated standalone script to <path>.
  --stdout         Print the generated standalone script to stdout.
  --check          Exit non-zero if the tracked standalone script is out of date.
EOF
}

mode="write"
output_path="$DEFAULT_OUTPUT_PATH"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output_path="${2:-}"
      [[ -n "$output_path" ]] || { echo "missing value for --output" >&2; exit 1; }
      shift 2
      ;;
    --stdout)
      mode="stdout"
      shift
      ;;
    --check)
      mode="check"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

tmp_output="$(mktemp)"
cleanup() {
  rm -f "$tmp_output"
}
trap cleanup EXIT

found_begin="false"
found_end="false"
inside_generated_block="false"

while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    '# BEGIN_GENERATED_MODULES')
      found_begin="true"
      inside_generated_block="true"
      printf '%s\n' "$line" >> "$tmp_output"
      printf '# This block is generated by tools/build-standalone.sh.\n' >> "$tmp_output"
      for module in "${MODULES[@]}"; do
        printf '\n# --- %s ---\n' "$module" >> "$tmp_output"
        cat "${ROOT_DIR}/${module}" >> "$tmp_output"
        printf '\n' >> "$tmp_output"
      done
      ;;
    '# END_GENERATED_MODULES')
      found_end="true"
      inside_generated_block="false"
      printf '%s\n' "$line" >> "$tmp_output"
      ;;
    *)
      if [[ "$inside_generated_block" == "false" ]]; then
        printf '%s\n' "$line" >> "$tmp_output"
      fi
      ;;
  esac
done < "$TEMPLATE_PATH"

if [[ "$found_begin" != "true" || "$found_end" != "true" ]]; then
  echo "template is missing generated module markers: ${TEMPLATE_PATH}" >&2
  exit 1
fi

case "$mode" in
  stdout)
    cat "$tmp_output"
    ;;
  check)
    if cmp -s "$tmp_output" "$output_path"; then
      echo "standalone script is up to date: ${output_path}"
    else
      echo "standalone script is out of date: ${output_path}" >&2
      exit 1
    fi
    ;;
  write)
    cat "$tmp_output" > "$output_path"
    chmod +x "$output_path"
    echo "wrote standalone script: ${output_path}"
    ;;
esac